language: node_js
node_js:
  - "5.6"
  - "stable"
before_install:
  - npm install -g bower
install:
  - npm install --no-optional
  - bower install
before_script:
  - npm install -g grunt-cli
script:
  - grunt build
branches:
  only:
    - master
